// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq57L9Lcxfua_roFvbID9_bLayGamKTmk',
    appId: '1:227758929265:web:fa5caa927da855e11772d0',
    messagingSenderId: '227758929265',
    projectId: 'dayly-6329b',
    authDomain: 'dayly-6329b.firebaseapp.com',
    storageBucket: 'dayly-6329b.firebasestorage.app',
    measurementId: 'G-21S7458B3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDC2d84DRQNYG2Nsft86DPbHIQKDXRrIs',
    appId: '1:227758929265:android:26eaac5618f2e13c1772d0',
    messagingSenderId: '227758929265',
    projectId: 'dayly-6329b',
    storageBucket: 'dayly-6329b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbhpyAhr1ZFhCHYZNlUc7ks738-z0g-Mk',
    appId: '1:227758929265:ios:0f770b371dbd14301772d0',
    messagingSenderId: '227758929265',
    projectId: 'dayly-6329b',
    storageBucket: 'dayly-6329b.firebasestorage.app',
    iosBundleId: 'com.example.dayly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbhpyAhr1ZFhCHYZNlUc7ks738-z0g-Mk',
    appId: '1:227758929265:ios:0f770b371dbd14301772d0',
    messagingSenderId: '227758929265',
    projectId: 'dayly-6329b',
    storageBucket: 'dayly-6329b.firebasestorage.app',
    iosBundleId: 'com.example.dayly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq57L9Lcxfua_roFvbID9_bLayGamKTmk',
    appId: '1:227758929265:web:7fc03ae8e1575c771772d0',
    messagingSenderId: '227758929265',
    projectId: 'dayly-6329b',
    authDomain: 'dayly-6329b.firebaseapp.com',
    storageBucket: 'dayly-6329b.firebasestorage.app',
    measurementId: 'G-MEEZ69MJHY',
  );
}
